@startuml

node "Message Broker Node" {
  database "SQLite" as DB
  component "Repository" as R
  component "Consensus Service" as CS
  component "Broker Service" as B

  component "Broker Server" as BS
  component "Node Server" as NS
}

actor/ "Publishers" as P
actor "Subscribers" as C
node "Other Nodes" as N

R --> DB
R <- B
B <- CS

B <-- BS
CS <-- BS
BS <-- C
BS <-- P

CS <-- NS
NS <-- N


@enduml
