@startuml

actor/ "US Publishers" as P1
actor/ "EU Publishers" as P2
actor/ "ASIA Publishers" as P3

actor "US Subscribers" as C1
actor "EU Subscribers" as C2
actor "ASIA Subscribers" as C3


cloud us-central {
  node "Node 1" as N1
}
cloud europe-west {
  node "Node 2" as N2
}
cloud asia-south {
  node "Node 3" as N3
}

N1 = N2
N2 == N3
N3 == N1

N1 <-- P1
N1 <-- C1

N2 <-- P2
N2 <-- C2

P3 -up-> N3
C3 -up-> N3

@enduml
