@startuml

actor/ "US Producers" as P1
actor/ "EU Producers" as P2
actor/ "ASIA Producers" as P3

actor "US Consumers" as C1
actor "EU Consumers" as C2
actor "ASIA Consumers" as C3


cloud us-central {
  node "Node 1" as N1
}
cloud europe-west {
  node "Node 2" as N2
}
cloud asia-south {
  node "Node 3" as N3
}

N1 = N2
N2 == N3
N3 == N1

N1 <-- P1
N1 <-- C1

N2 <-- P2
N2 <-- C2

P3 -up-> N3
C3 -up-> N3

@enduml
