@startuml

actor Publisher as P
box "Message Broker"
participant "Node 1" as N1
participant "Node 2" as N2
participant "Node 3" as N3
end box
actor Subscriber as S

N3 <- S : Subscribe
P -> N1 : Publish message
N1 -> N2 : Propose message
N1 -> N3 : Propose message
N1 <-- N2 : Ack message
N1 <-- N3 : Ack message
N1 -> N1 : Stable message
N1 -> N2 : Stable message
N1 -> N3 : Stable message
N3 -> S : Receive message
N3 <-- S : Ack message

@enduml