@startuml

actor "Publisher 1" as P1
box "Message Broker"
participant "Node 1" as N1
participant "Node 2" as N2
participant "Node 3" as N3
end box
actor "Publisher 2" as P2

N3 <- P2 : Publish msg B
P1 -> N1 : Publish msg A

N1 -> N2 : Propose A first msg
N1 <-- N2 : Ack A first msg

N3 -> N2 : Propose B first msg
activate N2

N1 -> N3 : Propose A first msg
N1 <-- N3 : Msg B before msg A

N1 -> N3 : Stable msg B before msg A

N1 -> N2 : Stable msg B before msg A
N2 --> N3 : Ack B first msg
deactivate N2

N3 -> N2 : Stable B first msg

N3 -> N1 : Stable B first msg

@enduml