@startuml
left to right direction

actor "Subscriber" as C

rectangle "Message Broker" {
  usecase "Authenticate" as A
  usecase "Connect" as CO
  usecase "Create topic" as CT
  usecase "Subscribe to topic" as ST
  usecase "Receive messages" as CS
  usecase "Unsubscribe from topic" as UT
}

C --> CO
C --> ST
C --> UT

CO ..> A : <<include>>
ST <.. CT : <<extend>>
ST <.. CS : <<extend>>
@enduml